include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    sort_constructors_first: ignore
  exclude:
    - lib/**/*.freezed.dart
    - lib/**/*.g.dart

linter:
  rules:
    public_member_api_docs: false
    depend_on_referenced_packages: false
    unnecessary_this: false

    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_constructors_in_immutables: true

    curly_braces_in_flow_control_structures: false
    require_trailing_commas: false
    lines_longer_than_80_chars: false

formatter:
  trailing_commas: preserve
  page_width: 100
