// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('DefaultFirebaseOptions have not been configured for web - '
          'you can reconfigure this by running the FlutterFire CLI again.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATxFJIhWAKHTLMgVR_xjWSc218M4LTiHM',
    appId: '1:236481695711:android:31016a3e286fd16ae23e6a',
    messagingSenderId: '236481695711',
    projectId: 'ustadia-student',
    storageBucket: 'ustadia-student.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU-nx8E_xZPIqB3sInDnFxJUEOGsOsY3Y',
    appId: '1:236481695711:ios:a1eb623df13b70b1e23e6a',
    messagingSenderId: '236481695711',
    projectId: 'ustadia-student',
    storageBucket: 'ustadia-student.firebasestorage.app',
    iosBundleId: 'uz.ustadia.user',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU-nx8E_xZPIqB3sInDnFxJUEOGsOsY3Y',
    appId: '1:236481695711:ios:a1eb623df13b70b1e23e6a',
    messagingSenderId: '236481695711',
    projectId: 'ustadia-student',
    storageBucket: 'ustadia-student.firebasestorage.app',
    iosBundleId: 'uz.ustadia.user',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4KGGwe832eZQqkLaueVrfbxagmu284mA',
    appId: '1:236481695711:web:2c37388993df1fd7e23e6a',
    messagingSenderId: '236481695711',
    projectId: 'ustadia-student',
    authDomain: 'ustadia-student.firebaseapp.com',
    storageBucket: 'ustadia-student.firebasestorage.app',
    measurementId: 'G-0CNHBW4D18',
  );
}
